#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/manuscript/full-draft.md"

SECTIONS=(
  "$ROOT_DIR/manuscript/sections/00-title.md"
  "$ROOT_DIR/manuscript/sections/01-introduction.md"
  "$ROOT_DIR/manuscript/sections/02-chapter-1.md"
  "$ROOT_DIR/manuscript/sections/03-chapter-2.md"
  "$ROOT_DIR/manuscript/sections/04-chapter-3.md"
  "$ROOT_DIR/manuscript/sections/05-conclusion.md"
  "$ROOT_DIR/manuscript/sections/06-bibliography.md"
)

{
  printf '<!-- Generated by scripts/assemble_thesis.sh on %s -->\n\n' "$(date '+%Y-%m-%d %H:%M:%S %Z')"

  for section in "${SECTIONS[@]}"; do
    if [[ -f "$section" ]]; then
      cat "$section"
      printf '\n\n'
    fi
  done
} > "$OUT_FILE"

printf 'Assembled %s\n' "$OUT_FILE"
